### ISSUE TITLE
Nytt felt i begrepspublisererer: "Forhold til kilde"

### ISSUE THREAD

**Issue by marittor** [brreg/begrepspubliserer#8]
P.t. høster begrepspubliserer kun Kilde til definisjon. For å bli mer konform med standard for begrepsbeskrivelser har vi lagt til et nytt felt som heter "forhold til kilde". I denne ligger ei kodeliste med verdiene: 
- Egendefinert
- Basert på kilde
- Sitat fra kilde

Vi har begynt å legge til dette på begrepene og vi ønsker derfor å få på plass høsting av feltet her snart. Jeg trenger altså at begrepspubliserer blir oppdatert til å hente ett nytt felt i tillegg til de andre feltene. 

Vi ønsker at dette skal vises i Felles begrepskatalog GUI på lignende måte som det høstes inn fra registreringsløsningene, (der slår man sammen tre felter, forhold til kilde, tittel og lenke til kilde - her trengs det å slå sammen to felter, altså input fra JIRAs forhold til kilde + kilde til definisjon utgjør kildefeltet i FBK portal)

**Comment by stigbd** [comment]
Har du felt-navna frå Jira på disse?

**Comment by marittor** [comment]
Gjelder feltet: "customfield_15610-val"

**Comment by frodegill** [comment]
Fixed (but it is still not possible to build and deploy it from Jenkins, as skos-ap-no-tools is not available in a public repo)
